# Wazuh App Copyright (C) 2021 Wazuh Inc. (License GPLv2)
version: '3.7'

services:
  wazuh:
    image: wazuh/wazuh-odfe:4.1.2
    hostname: wazuh-manager
    restart: unless-stopped
    ports:
      - "${MISTBORN_BIND_IP}:1514:1514"
      - "${MISTBORN_BIND_IP}:1515:1515"
      - "${MISTBORN_BIND_IP}:514:514/udp"
      - "${MISTBORN_BIND_IP}:55000:55000"
    environment:
      - FILEBEAT_SSL_VERIFICATION_MODE=none
    env_file:
      - ../.envs/.production/.wazuh
    volumes:
      - ossec_api_configuration:/var/ossec/api/configuration
      - ossec_etc:/var/ossec/etc
      - ossec_logs:/var/ossec/logs
      - ossec_queue:/var/ossec/queue
      - ossec_var_multigroups:/var/ossec/var/multigroups
      - ossec_integrations:/var/ossec/integrations
      - ossec_active_response:/var/ossec/active-response/bin
      - ossec_agentless:/var/ossec/agentless
      - ossec_wodles:/var/ossec/wodles
      - filebeat_etc:/etc/filebeat
      - filebeat_var:/var/lib/filebeat

volumes:
  ossec_api_configuration:
  ossec_etc:
  ossec_logs:
  ossec_queue:
  ossec_var_multigroups:
  ossec_integrations:
  ossec_active_response:
  ossec_agentless:
  ossec_wodles:
  filebeat_etc:
  filebeat_var:

networks:
  default:
    external:
      name: mistborn_default
